name: graphes
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Installation de graphviz
      run: sudo apt install graphviz
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Lancement graphviz
      run: ./run2.sh 
    - name: upload du resultat
      uses: actions/upload-artifact@v4
      with:
        name: result_graph
        path: *.svg
